---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
rm(list = ls())
```


```{r}
encuesta_mrp <- readRDS("pobreza/datos/encuesta_mrp.rds")
censo_mrp <- readRDS("pobreza/datos/censo_mrp.rds")
```

```{r}
censo_mrp <-   censo_mrp %>% 
    select(-n)

encuesta_mrp$dam <- encuesta_mrp %>% transmute(
  dam = case_when(dam == 01 ~ 1,
            dam == 02 ~ 2,
            dam == 03 ~ 3,
            dam == 04 ~ 4,
            dam == 05 ~ 5,
            dam == 06 ~ 6))
```

```{r}
library(SAEforest)
library(dplyr)
library(caret)
```

```{r}
pobreza <- encuesta_mrp$pobreza
X_covar <- encuesta_mrp %>% 
  select(area, sexo, anoest, edad, discapacidad)
```

```{r}
# Specific characteristics of Cross-validation
fitControl <- trainControl(method = "repeatedcv",
                           number = 5,
                           repeats = 1)

# Define a tuning-grid
merfGrid <- expand.grid(
  num.trees = 50,
  mtry = c(3, 7, 9),
  min.node.size = 10,
  splitrule = "variance"
)

tune_parameters(
  Y = pobreza,
  X = X_covar,
  data = encuesta_mrp,
  dName = "dam",
  trControl = fitControl,
  tuneGrid = merfGrid
)

### Step 2: Estimate MERFs and MSEs---------------------------------------------
model1 <-
  SAEforest_model(
    Y = income,
    X = X_covar,
    dName = "district",
    smp_data = eusilcA_smp,
    pop_data = eusilcA_pop,
    meanOnly = TRUE,
    MSE = "nonparametric",
    B = 10,
    B_adj = 30,
    mtry = 7
  )

#Example 1:
#Calculating point estimates and discussing basic generic functions

model1 <- SAEforest_model(Y = pobreza, X = X_covar, dName = "dam",
                         smp_data = encuesta_mrp, pop_data = censo_mrp)
```

