---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
rm(list = ls())
```


```{r}
x <- c('SAEforest','caret','dplyr')
lapply(x, require, character.only = TRUE)
```


```{r}
censo_mrp <- readRDS("ingreso/datos/censo_mrp.rds")
encuesta_mrp <- readRDS("ingreso/datos/encuesta_mrp.rds")
```


```{r}
encuesta_mrp$ingreso <- encuesta_mrp$ingreso + 1
```

```{r}
# debemos de quitar algunas variables
censo_mrp <- censo_mrp %>% 
  ungroup() %>% 
  select(-distrito, -n,-etnia) %>% 
  # select(-X2016_crops.coverfraction, -X2016_urban.coverfraction,
  #        -X2016_gHM, -accessibility, -accessibility_walking_only,
  #        -area1, -sexo2,-edad2,-edad3, -edad4,-edad5,-anoest2,
  #        -anoest3, -anoest4, -discapacidad1,-etnia1,-n,-etnia) %>% 
  mutate_if(is.character , as.factor) %>%  mutate(
  dam = recode(dam,
               "01" = 1,
               "02" = 2,
               "03" = 3,
               "04" = 4,
               "05" = 5,
               "06" = 6))
censo_mrp$dam <- as.factor(censo_mrp$dam)
summary(censo_mrp)
# Encuesta quitamos ingreso, lp, li y fep
encuesta_mrp <- encuesta_mrp %>% 
  select(area, sexo, edad, anoest, discapacidad, dam, ingreso) %>% 
  # select(-X2016_crops.coverfraction, -X2016_urban.coverfraction,
  #        -X2016_gHM, -accessibility, -accessibility_walking_only,
  #        -area1, -sexo2,-edad2,-edad3, -edad4,-edad5,-anoest2,
  #        -anoest3, -anoest4, -discapacidad1,-etnia1,-lp,-li,-fep,-ingreso) %>% 
    mutate(
  dam = recode(dam,
               "01" = 1,
               "02" = 2,
               "03" = 3,
               "04" = 4,
               "05" = 5,
               "06" = 6)) %>% 
  mutate_if(is.character, as.factor)

encuesta_mrp$dam <- as.factor(encuesta_mrp$dam)
summary(encuesta_mrp)
```

```{r}
### Step 1: Model tuning---------------------------------------------------

ingreso <- encuesta_mrp$ingreso
covar <- encuesta_mrp %>% select(-ingreso, -dam)

# Specific characteristics of Cross-validation
fitControl <- trainControl(method = "repeatedcv",
                           number = 5,
                           repeats = 1)

# Define a tuning-grid
merfGrid <- expand.grid(
  num.trees = 50,
  mtry = c(2,4,6),
  min.node.size = 10,
  splitrule = "variance"
)

tune_parameters(
  Y = ingreso,
  X = covar,
  data = encuesta_mrp,
  dName = "dam",
  trControl = fitControl,
  tuneGrid = merfGrid
)

### Step 2: Estimate MERFs and MSEs---------------------------------------------
model1 <-
  SAEforest_model(
    Y = ingreso,
    X = covar,
    dName = "dam",
    smp_data = encuesta_mrp,
    pop_data = censo_mrp,
    meanOnly = TRUE,
    MSE = "nonparametric",
    mtry = 4
  )

### Step 3: Assess the estimated model------------------------------------------
summary(model1)
plot(model1)

### Step 4: Extract the results------------------------------------------------- 
head(summarize_indicators(model1, MSE = TRUE, CV =TRUE))
```


# MERF con covariables

```{r}
rm(list = ls())
```


```{r}
x <- c('SAEforest','caret','dplyr')
lapply(x, require, character.only = TRUE)
```


```{r}
censo_mrp <- readRDS("ingreso/datos/censo_mrp1.rds")
encuesta_mrp <- readRDS("ingreso/datos/encuesta_mrp1.rds")
```


```{r}
encuesta_mrp$ingreso <- encuesta_mrp$ingreso + 1
```

```{r}
# debemos de quitar algunas variables
censo_mrp <- censo_mrp %>% 
  ungroup() %>% 
  select(-X2016_crops.coverfraction, -X2016_urban.coverfraction,
         -X2016_gHM, -accessibility, -accessibility_walking_only,
         -area1, -sexo2,-edad2,-edad3, -edad4,-edad5,-anoest2,
         -anoest3, -anoest4, -discapacidad1,-etnia1,-n,-etnia,
         -distrito) %>%
  mutate_if(is.character , as.factor) %>%  mutate(
  dam = recode(dam,
               "01" = 1,
               "02" = 2,
               "03" = 3,
               "04" = 4,
               "05" = 5,
               "06" = 6))
censo_mrp$dam <- as.factor(censo_mrp$dam)
summary(censo_mrp)
# Encuesta quitamos ingreso, lp, li y fep
encuesta_mrp <- encuesta_mrp %>% 
  select(-X2016_crops.coverfraction, -X2016_urban.coverfraction,
         -X2016_gHM, -accessibility, -accessibility_walking_only,
         -area1, -sexo2,-edad2,-edad3, -edad4,-edad5,-anoest2,
         -anoest3, -anoest4, -discapacidad1,-etnia1,-lp,-li,-fep,-pobreza) %>%
    mutate(
  dam = recode(dam,
               "01" = 1,
               "02" = 2,
               "03" = 3,
               "04" = 4,
               "05" = 5,
               "06" = 6)) %>% 
  mutate_if(is.character, as.factor)

encuesta_mrp$dam <- as.factor(encuesta_mrp$dam)
summary(encuesta_mrp)
```

```{r}
### Step 1: Model tuning---------------------------------------------------

ingreso <- encuesta_mrp$ingreso
covar <- encuesta_mrp %>% select(-ingreso, -dam)



# Specific characteristics of Cross-validation
fitControl <- trainControl(method = "repeatedcv",
                           number = 5,
                           repeats = 1)
# Define a tuning-grid
merfGrid <- expand.grid(
  num.trees = 50,
  mtry = c(3,6,9,12,15),
  min.node.size = 10,
  splitrule = "variance"
)

tune_parameters(
  Y = ingreso,
  X = covar,
  data = encuesta_mrp,
  dName = "dam",
  trControl = fitControl,
  tuneGrid = merfGrid
)

### Step 2: Estimate MERFs and MSEs---------------------------------------------

model1 <-
  SAEforest_model(
    Y = ingreso,
    X = covar,
    dName = "dam",
    smp_data = encuesta_mrp,
    pop_data = censo_mrp,
    meanOnly = TRUE,
    B = 10,
    B_adj = 30,
    MSE = "nonparametric",
    mtry = 3
  )

saveRDS(model1, file = "ingreso/datos/model1.rds")
```

```{r}
### Step 3: Assess the estimated model------------------------------------------

model1 <- readRDS("ingreso/datos/model1.rds")
summary(model1)
plot(model1)

``` 

```{r}
### Step 4: Extract the results------------------------------------------------- 
head(summarize_indicators(model1, MSE = TRUE, CV =TRUE))

```


```{r}
mod <- randomForest(ingreso ~ .,data = encuesta_mrp, mtry = 9, importance = TRUE,
             na.action = na.omit)
```

```{r}
pred <- predict(mod, newdata = censo_mrp, type = "response")

censo_mrp$pred <- pred
```





