---
output: html_document
editor_options: 
  chunk_output_type: console
---

Autor: Marco Espinoza
CEPAL - División de Estadística
fecha: mayo - 2024


# Librerías

```{r}
x <- c('tidyverse','survey','srvyr', 'data.table','gridExtra')
lapply(x, require, character.only = TRUE)
```

```{r}
rm(list = ls())
```

# Datos

## Encuesta

```{r}
encuesta_mrp <- readRDS("ingreso/datos/encuesta_mrp1.rds") %>% 
        mutate(
  region = recode(dam,
               "01" = "Central",
               "02" = "Chorotega",
               "03" = "Pacífico Central",
               "04" = "Brunca",
               "05" = "Huetar Caribe",
               "06" = "Huetar Norte")) %>%
  mutate(region = as.factor(region)) %>% 
  mutate_if(is.character, as.factor) %>% 
  mutate(dam = as.factor(dam))
```

## Diseño

```{r}
diseno <- encuesta_mrp  %>% 
  as_survey_design(weights = fep)
```

## Cálculo estimador directo

```{r}
media_est_srvyr <- svyby(
  ~ingreso,
  by = ~region,
  design = diseno,
  svymean
)
```

## Intervalos de confianza

```{r}
confint_int <- confint(svyby(formula = ~ingreso,
                             by = ~region,
                             design = diseno,
                             svymean))

confint_int <- data.table(confint_int, keep.rownames = TRUE)
colnames(confint_int) <- c("region","min_inter", "max_inter")

confint_int$ingreso <- media_est_srvyr$ingreso

```

# Primera predicción (GBlinear)

## Censo

```{r}
censo_mrp <- censo_mrp <- readRDS("ingreso/datos/censo_mrp1.rds") %>%  
      mutate(
  region = recode(dam,
               "01" = "Central",
               "02" = "Chorotega",
               "03" = "Pacífico Central",
               "04" = "Brunca",
               "05" = "Huetar Caribe",
               "06" = "Huetar Norte")) %>%
  mutate(region = as.factor(region))
```

```{r}
pred <- readRDS("ingreso/output/pred.rds")
```

```{r}
censo_mrp$pred_ingreso <- pred
```

## Calculo ingreso

```{r}
ingreso_dam <- censo_mrp %>% 
  group_by(region) %>% 
  summarise(
    ingreso = mean(pred_ingreso)
  ) 
```


```{r}
mapping <- rbind(media_est_srvyr[,-3], ingreso_dam)

estim <- c(rep("Directo", 6), rep("XGBoost", 6))

mapping <- cbind(mapping, estim)
```


## Gráfico

```{r}

p1 <- mapping %>%
  ggplot(aes(x = region, y = ingreso)) + geom_point(aes(color = estim), size = 2, position = "jitter") +
  scale_color_manual(values = c("red", "green")) +
  labs(title = "Validación para modelo de regresión", x = "Región de planificación", y = "Ingreso", col = "Modelo") +
  geom_errorbar(data = confint_int, aes(x = region, ymin = min_inter, ymax = max_inter)) +
  theme_minimal()

```

```{r}
saveRDS(p1, "ingreso/output/validacion_regre.rds")
```


# Segunda predicción (GBtree)

## Censo


```{r}
censo_mrp <- censo_mrp <- readRDS("ingreso/datos/censo_mrp1.rds") %>%  
      mutate(
  region = recode(dam,
               "01" = "Central",
               "02" = "Chorotega",
               "03" = "Pacífico Central",
               "04" = "Brunca",
               "05" = "Huetar Caribe",
               "06" = "Huetar Norte")) %>%
  mutate(region = as.factor(region))
```


```{r}
pred2 <- readRDS("ingreso/output/pred2.rds")
```

```{r}
censo_mrp$pred_ingreso <- pred2
```

## Calculo ingreso

```{r}
ingreso_dam <- censo_mrp %>% 
  group_by(region) %>% 
  summarise(
    ingreso = mean(pred_ingreso)
  ) 
```


```{r}
mapping <- rbind(media_est_srvyr[,-3], ingreso_dam)

estim <- c(rep("Directo", 6), rep("XGBoost", 6))

mapping <- cbind(mapping, estim)
```


## Gráfico

```{r}
p2 <- mapping %>%
  ggplot(aes(x = region, y = ingreso)) + geom_point(aes(color = estim), size = 2, position = "jitter") +
  scale_color_manual(values = c("red", "green")) +
  labs(title = "Validación para modelo de árbol", x = "Región de planificación", y = "Ingreso", col = "Modelo") +
  geom_errorbar(data = confint_int, aes(x = region, ymin = min_inter, ymax = max_inter)) +
  theme_minimal()
```


```{r}
saveRDS(p2, "ingreso/output/validacion_arbol.rds")
```

# Comparación

```{r}
p1 <- readRDS("ingreso/output/validacion_regre.rds")
p2 <- readRDS("ingreso/output/validacion_arbol.rds")
```


```{r}
grid.arrange(p1, p2)
```

# Benchmark



