---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
rm(list = ls())
```


# Librerias

```{r}
x <- c('rpart','rattle','DT','adabag','randomForest','haven','dplyr')
lapply(x, require, character.only = TRUE)
```

# Base de datos

```{r}
load("./data/ingreso/encuesta_df_agg.Rdata")
```

```{r}
head(encuesta_df_agg)
```

- La variable ingreso es inicialmente, ingreso per capita del hogar. No obstante, luego esta se 
transforma y se crea el ingreso promedio per capita. 

# Transformaciones

```{r}
encuesta_df_agg$area <- as.factor(encuesta_df_agg$area)

encuesta_df_agg <- encuesta_df_agg %>%
  select(-n, -dam, -ingreso) %>%
  mutate_if(is.character, as.factor)

save(encuesta_df_agg, file = "./data/ingreso/encuesta_df_agg.Rdata")
summary(encuesta_df_agg)
```

# Base de datos de entrenamiento y prueba

```{r, warning=FALSE}
RNGkind(sample.kind = "Rounding")
```

```{r}
set.seed(10)
n = nrow(encuesta_df_agg)
s = sample(1:n, round(0.8*n))

train = encuesta_df_agg[s, ]
test = encuesta_df_agg[-s, ]
```

## Dimensiones

```{r}
dim(train)
dim(test)
```

# Arbol de decisión

```{r}
mod = rpart(pobreza ~ ., method = "class", data = train)
```

```{r}
fancyRpartPlot(mod, palettes = c("Greens","Reds"))
```

